---
language: go
go:
  - 1.x
before_install:
  - node -v
  - npm -v
install:
  - npm install
  - go get -t ./...
  # https://github.com/golang/lint/issues/397
  # - go get -u golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/gosimple
  - go get honnef.co/go/tools/cmd/unused
  - go get honnef.co/go/tools/cmd/staticcheck
script:
  - npm run commitlint-travis
  - bash lint.sh
  - bash codecov-test.sh
after_success:
  - bash codecov.sh
